### ISSUE TITLE
Correct path to ctk-building.html and other information files

### ISSUE THREAD

**Issue by jelabarre59** [cafe-desktop/ctk#23]
For https://github.com/cafe-desktop/ctk/blob/master/INSTALL.in, the "Details" section points to an invalid location for the detailed install information files.  Probably a factor of the original renaming of the libraries from GTK to CTK (obviously CTK would not be on Gnome's website)

Did not find an equivalent path in the CTK source directories.

**Comment by sc0w** [comment]
- ` docs/reference/ctk/html/ctk-building.html` <- I will add more info, this file will appear if you build with `--enable-gtk-doc`, after the install it is also in `/usr/share/gtk-doc/html/ctk3/ctk-building.html`, and the source is in https://github.com/cafe-desktop/ctk/blob/master/docs/reference/ctk/building.sgml

- http://library.gnome.org/devel/ctk/stable/ctk-building.html <- I will remove it, the documentation isn't online (maybe in the future), and a lot of `gnome` in code needs changes
