### ISSUE TITLE
Docs about differences to GTK3/4 and migration guide

### ISSUE THREAD

**Issue by Thaodan** [cafe-desktop/ctk#25]
I would be very useful if your project would contain documentation of the difference/divergence from GTK3.

Also how to migrate from GTK3.
As a user of GTK apps outside of GNOME I find a GTK3 fork very appealing.

**Comment by sc0w** [comment]
I think the job is done with https://github.com/cafe-desktop/ctk/commit/603d1e7fba38417b566f562cb19b1281167f6a1a and https://github.com/cafe-desktop/ctk/commit/b2e87db84639cf9bca7b741c9c51e713c3fe864e

**Comment by Thaodan** [comment]
Looks good to me however I think just renaming in a `s/g/c/` why might
not be the easiest option for most projects

Something like gtk-compat would be better.

**Comment by sc0w** [comment]
> Looks good to me however I think just renaming in a `s/g/c/` why might not be the easiest option for most projects 

you can use a script, like this:
https://github.com/cafe-desktop/cafe-dev-scripts/blob/master/travis/build/utils/replace.sh

syntax: `./replace.sh gtk ctk` for example

> Something like gtk-compat would be better.

I dont know what is it, which is the homepage?

**Comment by Thaodan** [comment]
>> Something like gtk-compat would be better.
>
> I dont know what is it, which is the homepage?

It's just an idea of a compat package which essentially provides
all the GTK symbols so CTK can be used as a drop in dependency if so
desired.
The issue is that projects don't want to support CTK and GTK when it
essentially means that they have to duplicate their codepath.

**Comment by sc0w** [comment]
probably all the words affected are inside:

https://github.com/cafe-desktop/ctk/blob/master/docs/reference/ctk/ctk3-sections.txt

https://github.com/cafe-desktop/ctk/blob/master/docs/reference/cdk/cdk3-sections.txt

https://github.com/cafe-desktop/ctk/blob/master/docs/reference/libcail-util/cail-libcail-util3-sections.txt
